### ISSUE TITLE
How to Set the Value of K and Address Inconsistent Results in Correcting Single or All Potential Mediators or Confounders"

### ISSUE THREAD

**Issue by qxliu686** [ZhaotongL/MVMR-cML#4]
Hello, I hope you receive this message. Fantastic work! 

 **I have two questions.** Firstly, I noticed in the example that you set K (the number of invalid instrumental variables) to 0 to 20. In exploring the MVMR study of eight metabolic factors related to coronary heart disease after data harmonization, I observed that only a little over 100 IVs remained. I noticed that you did not pick GWAS with the maximum sample size or SNPs number for relevant traits, such as the SNP count for FG being only 64,432. When I choose the maximum sample size, I end up with **over 700 IVs** ,**Should I significantly increase the setting for K, perhaps to 300?** However, this would significantly extend the computation time. Do you have any recommendations for this?

Secondly, in investigating the causal association between a certain factor (A) and coronary heart disease, various robust methods in UVMR show significant results. In the MVMR stage, **when I include all eight metabolic factors in the model** (GWAS selecting the maximum sample size for the European population), I end up with over 700 instrumental variables, and **the causal effect of A remains significant (beta= -0.15, se = 0.02, p = 1e-15).** However, **when I include only A and SBP in the MVMR model, the causal effect of A becomes non-significant (beta=-0.03, se=0.02, p=0.12).** How would you interpret this result? Could it be due to too many invalid instrumental variables, not meeting the MV-A2 assumption? Any advice on this issue would be greatly appreciated.

**Comment by ZhaotongL** [comment]
> Hello, I hope you receive this message. Fantastic work!
> 
> **I have two questions.** Firstly, I noticed in the example that you set K (the number of invalid instrumental variables) to 0 to 20. In exploring the MVMR study of eight metabolic factors related to coronary heart disease after data harmonization, I observed that only a little over 100 IVs remained. I noticed that you did not pick GWAS with the maximum sample size or SNPs number for relevant traits, such as the SNP count for FG being only 64,432. When I choose the maximum sample size, I end up with **over 700 IVs** ,**Should I significantly increase the setting for K, perhaps to 300?** However, this would significantly extend the computation time. Do you have any recommendations for this?
> 
> Secondly, in investigating the causal association between a certain factor (A) and coronary heart disease, various robust methods in UVMR show significant results. In the MVMR stage, **when I include all eight metabolic factors in the model** (GWAS selecting the maximum sample size for the European population), I end up with over 700 instrumental variables, and **the causal effect of A remains significant (beta= -0.15, se = 0.02, p = 1e-15).** However, **when I include only A and SBP in the MVMR model, the causal effect of A becomes non-significant (beta=-0.03, se=0.02, p=0.12).** How would you interpret this result? Could it be due to too many invalid instrumental variables, not meeting the MV-A2 assumption? Any advice on this issue would be greatly appreciated.

Hi Qiuxuan,

Thanks for your interest! For your first question, yes, I would suggest picking a larger K instead of just 20 as shown in the example. You may want to try to use the non-DP version (or set num_pert=1) first to have a rough idea of what range of K_hat might be estimated by MVMR-cML-BIC. Then you can increase the boundary based on that number. In terms of speeding up the computation, another way is to parallelize the data perturbation. For example, you may have 200 jobs and each of them only runs one perturbation, and then you can summarize across the 200 perturbations, which is essentially what MVMR-cML-DP is doing under the hood.

For your second question, there could be several possible explanations. First, as you suggested, there could be an increasing number of invalid IVs for A as we are adjusting fewer potential pleiotropic pathways. Second, the effect that MVMR model models is the direct effect of A on the outcome, conditional on other exposures included in the model. So it is also expected to see different estimates of A on the outcome as we are adjusting two different sets of exposures here. Another possible reason you may want to check is if your GWAS dataset for exposure is adjusted by other covariates, which will also affect your interpretation of estimated coefficients in the MVMR model (see https://www.medrxiv.org/content/10.1101/2022.07.19.22277803v1).
